version: "3"

services:
  main_bot:
    build:
      context: .
      dockerfile: dockerfile

    env_file:
      - .env
    volumes:
      - "./logs:/app/logs"
    depends_on:
      - redis
      - db
      
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}


    command: ["redis-server", "--appendonly", "yes"]
  
  db:
    image: mongo:4.4
    restart: always

#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example

  
volumes:
  redis_data:
